### ISSUE TITLE
/assets/images/wood-2.png missing from GitHub hosting?

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/neural-neighbors#15]
Seems like the image is committed correctly but is 404'ing on github.io

**Comment by ghost** [comment]
It looks like it’s located here: https://github.com/YaleDHLab/neural-neighbors/blob/master/assets/images/wood-2.png

Will review the URL to see if something is off…

Monica



On Sep 18, 2017, at 11:17 AM, Peter Leonard <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems like the image is committed correctly but is 404'ing on github.io<http://github.io>

**Comment by pleonard212** [comment]
I feel like the line in the CSS is correct and for some reason that asset just isn't making it to .io?

**Comment by ghost** [comment]
Hi, Peter -

Doug pointed me to using a long image address — I’ve created a pull request. Do you want to take a look and merge to see if it works?

Thanks,
Monica


On Sep 18, 2017, at 11:45 AM, Peter Leonard <notifications@github.com<mailto:notifications@github.com>> wrote:


I feel like the line in the CSS is correct and for some reason that asset just isn't making it to .io?

**Comment by duhaime** [comment]
Hosting images on Github Pages is a little funny, in part because the repository name is added as a directory path on the deployed domain, and in part because the path to image files needs to point to the raw image, so:
https://github.com/YaleDHLab/neural-neighbors/blob/master/assets/images/wood-2.png

needs to be changed to:
https://github.com/YaleDHLab/neural-neighbors/blob/master/assets/images/wood-2.png?raw=true

or:
`url('/assets/images/wood-2.png')`

needs to be changed to:
`url('/neural-neighbors/assets/images/wood-2.png')`

**Comment by pleonard212** [comment]
Thx! All set now...
